export const MEDICINE_TYPES = [
  "CAPSULE",
  "INJECTION",
  "DROP",
  "DROPS",
  "DROPPER",
  "GLOBUS",
  "DRAM",
  "TABLET",
  "SOLUTION",
  "GEL",
  "SYRUP",
  "SUSPENSION",
  "CREAM",
  "LIQUID",
  "LOTION",
  "SACHET",
  "OINTMENT",
  "POWDER",
  "INHALER",
  "SPRAY",
  "SUPPOSITORY",
  "EMULSION",
  "BALM",
  "SOAP",
  "SHAMPOO",
  "FACEWASH",
  "TEASPOON",
  "AS_PER_NEED",
  "HALF_HOUR_BEFORE_MEAL",
  "FIVE_TIMES_A_DAY",
  "PO",
  "IV",
  "IM",
  "IG",
  "SC",
  "SL",
  "PR",
] as const;


export const MEDICINE_TYPE_LABELS: Record<(typeof MEDICINE_TYPES)[number], string> = {
  CAPSULE: "Capsule",
  INJECTION: "Injection",
  DROP: "Drop",
  DROPS: "Drops",
  DROPPER: "Dropper",
  GLOBUS: "Globus",
  DRAM: "Dram",
  TABLET: "Tablet",
  SOLUTION: "Solution",
  GEL: "Gel",
  SYRUP: "Syrup",
  SUSPENSION: "Suspension",
  CREAM: "Cream",
  LIQUID: "Liquid",
  LOTION: "Lotion",
  SACHET: "Sachet",
  OINTMENT: "Ointment",
  POWDER: "Powder",
  INHALER: "Inhaler",
  SPRAY: "Spray",
  SUPPOSITORY: "Suppository",
  EMULSION: "Emulsion",
  BALM: "Balm",
  SOAP: "Soap",
  SHAMPOO: "Shampoo",
  FACEWASH: "Facewash",
  TEASPOON: "Teaspoon",
  AS_PER_NEED: "As per need",
  HALF_HOUR_BEFORE_MEAL: "Half hour before meal",
  FIVE_TIMES_A_DAY: "Five times a day",
  PO: "PO - per oral",
  IV: "IV - intravenous",
  IM: "IM - intramuscular",
  IG: "IG - intragluteal",
  SC: "SC - subcutaneous",
  SL: "SL - sublingual",
  PR: "PR - per rectal",
};